INSERT INTO COUNTRY (NAME) VALUES ('SWEDEN');
INSERT INTO COUNTRY (NAME) VALUES ('INDIA');
INSERT INTO COUNTRY (NAME) VALUES ('RUSSIA');
INSERT INTO COUNTRY (NAME) VALUES ('CANADA');
INSERT INTO COUNTRY (NAME) VALUES ('BRAZIL');
INSERT INTO COUNTRY (NAME) VALUES ('AUSTRALIA');
INSERT INTO COUNTRY (NAME) VALUES ('ARGENTINA');
INSERT INTO COUNTRY (NAME) VALUES ('FINLAND');
INSERT INTO COUNTRY (NAME) VALUES ('SUDAN');
INSERT INTO COUNTRY (NAME) VALUES ('NORWAY');



